[task_config]
includes = ["bin"]

[tasks.format]
description = "Format all files"
alias = ["fmt"]
depends = ["format:**"]

[tasks.lint]
description = "Lint all files"
alias = ["l"]
depends = ["lint:**"]

[tools]
"cargo:cargo-audit" = "latest"
"cargo:cargo-llvm-cov" = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:cargo-outdated" = "latest"
"cargo:cargo-sort" = "latest"
editorconfig-checker = "latest"
markdownlint-cli2 = "latest"
taplo = "latest"
node = "latest"

[[tools.rust]]
components = "clippy"
version = "latest"

[[tools.rust]]
components = "rustfmt"
version = "nightly"
